import { Fragment } from 'react';
import Home from '../components/Home';
import Head from 'next/head'
import { userService } from '../services/user.service';
export default function HomePage(props) {

    return (
        <Fragment>
            <Head>
                <title>Task</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Home data={props.data} />
        </Fragment>
    )


}

export async function getStaticProps(context) {
    let data = await userService.getAll();
    return {
        props: { data },
        revalidate: 10
    }
}
